module.exports = [
  {
    ignores: ['node_modules', 'dist', 'build'],
  },
  {
    languageOptions: {
      ecmaVersion: 2021,
      sourceType: 'module',
      globals: {
        // Browser globals
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        fetch: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        FormData: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileList: 'readonly',
        XMLHttpRequest: 'readonly',
        EventSource: 'readonly',
        WebSocket: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        Promise: 'readonly',
        // jQuery
        jQuery: 'readonly',
        $: 'readonly',
        // DOM
        Element: 'readonly',
        Node: 'readonly',
        NodeFilter: 'readonly',
        HTMLElement: 'readonly',
        SVGElement: 'readonly',
        Event: 'readonly',
        CustomEvent: 'readonly',
        MouseEvent: 'readonly',
        KeyboardEvent: 'readonly',
        TouchEvent: 'readonly',
        // Custom globals
        globalThis: 'readonly',
        geweb_aisearch: 'readonly',
        GewebAISearchSourceMethods: 'readonly',
        GewebAisearchMarkdown: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-unused-vars': 'error',
      'no-console': 'warn',
      'eqeqeq': 'error',
      'curly': 'error',
      'brace-style': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'no-implicit-globals': 'error',
      'semi': 'error',
      'prefer-arrow-callback': 'warn',
      'no-empty': 'warn',
      'no-fallthrough': 'error',
    },
  },
];
